"""Unified feature engineering for training and live inference.

All features are treated as part of feature_cols per asset (no separate TA toggle).
"""

import numpy as np
import pandas as pd


USDCNH_FEATURE_COLS = [
    "Log_Returns",
    "volatility_dcp",
    "momentum_rsi",
    "Ret_Sum_16",
    "volatility_bbp",
    "momentum_ao",
    "trend_cci",
    "momentum_tsi",
    "trend_vortex_ind_neg",
    "trend_vortex_ind_pos",
    "AO_15m",
    "MFI_20",
    "Vol_Ratio",
    "BB_PctB",
    "Donchian_Pos_20",
    "ADX_4H",
    "AO_4H",
    "ADX_1D",
    "AO_1D",
    "Ret_Sum_8",
    "Ret_Sum_16",
    "AO_15m_Diff4",
    "AO_4H_Diff4",
    "AO_1D_Diff1",
    "MFI_20_Diff1",
    "AO15_x_VolRatio",
    "Session_Asia",
    "Volume",
    "RSI_14",
    "MACD_Hist",
    "VWAP_Dist",
    "OBV_Diff4",
]

CORN_FEATURE_COLS = [
    "Log_Returns",
    "volatility_dcp",
    "momentum_rsi",
    "volatility_bbp",
    "momentum_ao",
    "trend_cci",
    "momentum_tsi",
    "trend_macd",
    "AO_15m",
    "MFI_20",
    "Vol_Ratio",
    "BB_PctB",
    "Donchian_Pos_20",
    "ADX_4H",
    "AO_4H",
    "ADX_1D",
    "AO_1D",
    "Ret_Sum_8",
    "Ret_Sum_16",
    "AO_15m_Diff4",
    "AO_4H_Diff4",
    "AO_1D_Diff1",
    "MFI_20_Diff1",
    "AO15_x_VolRatio",
    "Session_Asia",
    "Volume",
    "StochK_14",
    "OBV_Diff4",
    "VolRank_2W",
]

FEATURE_SETS = {
    "USDCNH": USDCNH_FEATURE_COLS,
    "CORN": CORN_FEATURE_COLS,
    "default": USDCNH_FEATURE_COLS,
}


def get_all_ta_feature_cols(colprefix: str = "ta_") -> list:
    """Return all feature names generated by ta.add_all_ta_features.

    The list is generated dynamically from the installed ta version so you can
    keep a complete candidate set for later feature selection.
    """
    from ta import add_all_ta_features

    n = 300
    idx = np.arange(n, dtype=float)

    # Synthetic but valid OHLCV input to ensure all TA features can be built.
    close = 100.0 + 0.02 * idx + np.sin(idx / 12.0)
    open_ = close * (1.0 + 0.0005 * np.cos(idx / 7.0))
    high = np.maximum(open_, close) * 1.002
    low = np.minimum(open_, close) * 0.998
    volume = 1000.0 + 10.0 * np.mod(idx, 20)

    base = pd.DataFrame(
        {
            "open": open_,
            "high": high,
            "low": low,
            "close": close,
            "volume": volume,
        }
    )

    out = add_all_ta_features(
        base.copy(),
        open="open",
        high="high",
        low="low",
        close="close",
        volume="volume",
        fillna=False,
        colprefix=colprefix,
    )
    return sorted([c for c in out.columns if c not in base.columns])


def _asset_key(asset: str) -> str:
    key = (asset or "default").upper()
    if key not in FEATURE_SETS:
        return "default"
    return key


def _dedupe_keep_order(cols: list) -> list:
    seen = set()
    out = []
    for c in cols:
        if c not in seen:
            seen.add(c)
            out.append(c)
    return out


def get_feature_cols(asset: str) -> list:
    return _dedupe_keep_order(FEATURE_SETS[_asset_key(asset)])


def _get_col(df: pd.DataFrame, *names: str) -> pd.Series:
    for n in names:
        if n in df.columns:
            return df[n]
    return pd.Series(np.nan, index=df.index)


def _rolling_percentile_rank(s: pd.Series, window: int) -> pd.Series:
    return s.rolling(window).apply(lambda x: float(pd.Series(x).rank(pct=True).iloc[-1]), raw=False)


def _rsi(close: pd.Series, period: int = 14) -> pd.Series:
    delta = close.diff()
    up = delta.clip(lower=0.0)
    down = -delta.clip(upper=0.0)
    up_ema = up.ewm(span=period, adjust=False).mean()
    down_ema = down.ewm(span=period, adjust=False).mean()
    rs = up_ema / (down_ema + 1e-10)
    return 100.0 - (100.0 / (1.0 + rs))


def build_all_features(df: pd.DataFrame, asset: str) -> pd.DataFrame:
    """Build full feature set for an asset in one pass.

    Expects base MTF columns already present (AO_15m, MFI_20, AO_4H, AO_1D, etc.).
    Also supports both train-style (Close/Volume) and live-style (close/volume) names.
    """
    out = df.copy()

    close = _get_col(out, "Close", "close")
    high = _get_col(out, "High", "high")
    low = _get_col(out, "Low", "low")
    volume = _get_col(out, "Volume", "volume").astype(float)

    # Base columns if missing in live path.
    if "Log_Returns" not in out.columns:
        out["Log_Returns"] = np.log(close).diff()

    if "Vol_Ratio" not in out.columns and {"ATR_Fast", "ATR_Slow"}.issubset(out.columns):
        atr_slow = out["ATR_Slow"].replace(0, np.nan)
        out["Vol_Ratio"] = (out["ATR_Fast"] / atr_slow).replace([np.inf, -np.inf], np.nan)

    if "BB_PctB" not in out.columns and {"BB_Upper", "BB_Lower"}.issubset(out.columns):
        bb_range = (out["BB_Upper"] - out["BB_Lower"]).replace(0, np.nan)
        out["BB_PctB"] = ((close - out["BB_Lower"]) / bb_range).replace([np.inf, -np.inf], np.nan)

    if "Donchian_Pos_20" not in out.columns and {"Donchian_Upper_20", "Donchian_Lower_20"}.issubset(out.columns):
        donch_range = (out["Donchian_Upper_20"] - out["Donchian_Lower_20"]).replace(0, np.nan)
        out["Donchian_Pos_20"] = ((close - out["Donchian_Lower_20"]) / donch_range).replace([np.inf, -np.inf], np.nan)

    # Derived shared features.
    out["Ret_Sum_8"] = out["Log_Returns"].rolling(8).sum()
    out["Ret_Sum_16"] = out["Log_Returns"].rolling(16).sum()
    out["AO_15m_Diff4"] = out["AO_15m"].diff(4)
    out["AO_4H_Diff4"] = out["AO_4H"].diff(4)
    out["AO_1D_Diff1"] = out["AO_1D"].diff(1)
    out["MFI_20_Diff1"] = out["MFI_20"].diff(1)
    out["AO15_x_VolRatio"] = out["AO_15m"] * out["Vol_Ratio"]

    if isinstance(out.index, pd.DatetimeIndex):
        out["Session_Asia"] = ((out.index.hour >= 0) & (out.index.hour < 8)).astype(float)
    else:
        dt = pd.to_datetime(out.get("Datetime"), errors="coerce")
        out["Session_Asia"] = ((dt.dt.hour >= 0) & (dt.dt.hour < 8)).astype(float)

    out["Volume"] = volume

    # Normalize ta_ prefixed columns to non-prefixed names if source data uses ta_ naming.
    ta_aliases = {
        "ta_volatility_dcp": "volatility_dcp",
        "ta_momentum_rsi": "momentum_rsi",
        "ta_volatility_bbp": "volatility_bbp",
        "ta_momentum_ao": "momentum_ao",
        "ta_trend_cci": "trend_cci",
        "ta_momentum_tsi": "momentum_tsi",
        "ta_trend_vortex_ind_neg": "trend_vortex_ind_neg",
        "ta_trend_vortex_ind_pos": "trend_vortex_ind_pos",
        "ta_trend_macd": "trend_macd",
    }
    for src, dst in ta_aliases.items():
        if dst not in out.columns and src in out.columns:
            out[dst] = out[src]

    # Ensure newly selected TA-style columns exist even when not precomputed upstream.
    ta_needed = {
        "volatility_dcp",
        "momentum_rsi",
        "volatility_bbp",
        "momentum_ao",
        "trend_cci",
        "momentum_tsi",
        "trend_macd",
        "trend_vortex_ind_neg",
        "trend_vortex_ind_pos",
    }
    missing_ta = [c for c in ta_needed if c not in out.columns]
    if missing_ta:
        try:
            from ta import add_all_ta_features

            ta_src = pd.DataFrame(
                {
                    "open": _get_col(out, "Open", "open"),
                    "high": high,
                    "low": low,
                    "close": close,
                    "volume": volume,
                },
                index=out.index,
            )
            ta_full = add_all_ta_features(
                ta_src.copy(),
                open="open",
                high="high",
                low="low",
                close="close",
                volume="volume",
                fillna=False,
                colprefix="",
            )
            for c in missing_ta:
                if c in ta_full.columns:
                    out[c] = ta_full[c]
        except Exception:
            # Keep pipeline resilient if ta features cannot be generated in this path.
            for c in missing_ta:
                if c not in out.columns:
                    out[c] = np.nan

    # Asset-specific TA features are still part of unified feature_cols.
    key = _asset_key(asset)

    if key == "USDCNH":
        out["RSI_14"] = _rsi(close, 14)
        ema12 = close.ewm(span=12, adjust=False).mean()
        ema26 = close.ewm(span=26, adjust=False).mean()
        macd = ema12 - ema26
        signal = macd.ewm(span=9, adjust=False).mean()
        out["MACD_Hist"] = macd - signal

        tp = (high + low + close) / 3.0
        vwap = (tp * volume).rolling(32).sum() / (volume.rolling(32).sum() + 1e-10)
        out["VWAP_Dist"] = (close / vwap - 1.0).replace([np.inf, -np.inf], np.nan)

        obv = (np.sign(close.diff()) * volume).fillna(0.0).cumsum()
        out["OBV_Diff4"] = obv.diff(4)

    if key == "CORN":
        low14 = low.rolling(14).min()
        high14 = high.rolling(14).max()
        out["StochK_14"] = 100.0 * (close - low14) / (high14 - low14 + 1e-10)

        obv = (np.sign(close.diff()) * volume).fillna(0.0).cumsum()
        out["OBV_Diff4"] = obv.diff(4)

        out["VolRank_2W"] = _rolling_percentile_rank(volume, window=96)

    return out
